name: "yolov26_postprocess"
backend: "python"
max_batch_size: 64
default_model_filename: "postprocess.py"

input [
  {
    name: "DETECTION_OUTPUT"
    data_type: TYPE_FP32
    dims: [ 300, 6 ]  # onnx输出维度
  },
  {
    name: "IMAGE_SHAPE"
    data_type: TYPE_INT32
    dims: [ 2 ]  # heigh 和 width
  },
  {
    name: "SCALE"
    data_type: TYPE_FP32
    dims: [ 1 ]
  },
  {
    name: "PADDING"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

output [
  {
    name: "OUTPUT_RESULTS"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

# 参数配置：置信度阈值
parameters: {
  key: "CONF_THRESHOLD"
  value: { string_value: "0.25" }
}

instance_group [
  {
    count: 2
    kind: KIND_CPU
  }
]