name: "deeplabv3_ensemble"
platform: "ensemble"
max_batch_size: 128

input [
    {
        name: "RAW_IMAGE"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]

output [
    {
        name: "OUTPUT_RESULTS"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]

ensemble_scheduling {
    step [
        {
            model_name: "deeplabv3_preprocess"
            model_version: -1
            input_map {
                key: "RAW_IMAGE"
                value: "RAW_IMAGE"
            }
            output_map [
                {
                    key: "PREPROCESSED_IMAGE"
                    value: "preprocessed_image"
                },
                {
                    key: "IMAGE_SHAPE"
                    value: "IMAGE_SHAPE"
                }
            ]
        },
        {
            model_name: "deeplabv3_inference"
            model_version: -1
            input_map {
                key: "input"
                value: "preprocessed_image"
            }
            output_map {
                key: "output"
                value: "output"
            }
        },
        {
            model_name: "deeplabv3_postprocess"
            model_version: -1
            input_map [
                {
                    key: "MASKS"
                    value: "output"
                },
                {
                    key: "IMAGE_SHAPE"
                    value: "IMAGE_SHAPE"
                }
            ]
            output_map {
                key: "OUTPUT_RESULTS"
                value: "OUTPUT_RESULTS"
            }
        }
    ]
}