name: "yolov26_inference"
backend: "onnxruntime"
default_model_filename: "coco_yolo26s_fp16.onnx"
# backend: "tensorrt"
# default_model_filename: "coco_yolo26s_fp16.plan"
max_batch_size: 64  # 支持动态批处理（推荐），或设置为固定值如 1


input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3, 640, 640]  # 固定输入尺寸，NCHW 格式
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [300, 6]  # 输出维度，[batch, 300, 6]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]  # 使用第 0 号 GPU（A10）
  }
]